name: Checker

on:
  pull_request_target:
    branches: [ "main" ]
    types: [ opened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Read mail address
        id: mail-addr-reader
        run: echo "MAILER_TO=`cat mail.txt`" >> "$GITHUB_OUTPUT"
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: ${{secrets.MAILER_SERVER}}
          server_port: 465
          secure: true
          username: ${{secrets.MAILER_USERNAME}}
          password: ${{secrets.MAILER_PASSWORD}}
          subject: Flag for ${{github.event.pull_request.user.login}}
          to: ${{steps.mail-addr-reader.outputs.MAILER_TO}}
          from: ${{secrets.MAILER_FROM}}
          body: ${{secrets.FLAG}}
      - name: Close PR
        if: always()
        run: gh pr close ${{github.event.pull_request.number}}
        env:
          GH_TOKEN: ${{secrets.GH_REPO_TOKEN}}
